---
- name: Check amazon linux 2
  shell: LANG=C yum info installed system-release | awk '/^Release/ { print $3 }' | grep -q 'amzn2'
  ignore_errors: True
  register: check_al2
  check_mode: no
  changed_when: no

- name: Check exists Downloads directory
  stat:
    path: /tmp/Downloads
  register: check_dl_dir
  when: check_al2.rc == 0

- name: Make directory for Downloads
  file:
    path: /tmp/Downloads
    state: directory
    owner: root
    group: root
    mode: 0777
  when: check_al2.rc == 0 and (check_dl_dir.stat.exists != true or check_dl_dir.stat.isdir != true)

- name: Download cache-stnsd
  get_url:
    url: "https://github.com/STNS/cache-stnsd/releases/download/v{{cache_stnsd_version}}/cache-stnsd-{{cache_stnsd_version}}-1.x86_64.el7.rpm"
    dest: /tmp/Downloads
  when: check_al2.rc == 0

- name: Check exists cache-stnsd
  stat:
    path: "/tmp/Downloads/cache-stnsd-{{cache_stnsd_version}}-1.x86_64.el7.rpm"
  register: check_cache_stnsd
  when: check_al2.rc == 0

- name: Install cache-stnsd
  yum:
    name: /tmp/Downloads/cache-stnsd-{{cache_stnsd_version}}-1.x86_64.el7.rpm
    state: present
  become: yes
  when: check_al2.rc == 0 and (check_cache_stnsd.stat.exists == true and check_cache_stnsd.stat.isreg == true)

- name: Download libnss-stns
  get_url:
    url: "https://github.com/STNS/libnss/releases/download/v{{libnss_version}}/libnss-stns-v2-{{libnss_version}}-1.x86_64.el7.rpm"
    dest: /tmp/Downloads
  when: check_al2.rc == 0

- name: Check exists libnss-stns
  stat:
    path: "/tmp/Downloads/libnss-stns-v2-{{libnss_version}}-1.x86_64.el7.rpm"
  register: check_libnss_stns
  when: check_al2.rc == 0

- name: Install libnss-stns
  yum:
    name: /tmp/Downloads/libnss-stns-v2-{{libnss_version}}-1.x86_64.el7.rpm
    state: present
  become: yes
  when: check_al2.rc == 0 and (check_libnss_stns.stat.exists == true and check_libnss_stns.stat.isreg == true)

- name: Modify /etc/nsswitch.conf
  copy : >
    src=roles/stns-client/templates/etc/nsswitch.conf.j2
    dest=/etc/nsswitch.conf
    backup=yes
  become: yes
  when: check_al2.rc == 0

- name: Modify /etc/pam.d/sshd
  lineinfile: dest=/etc/pam.d/sshd line="{{item}}" backup=yes
  with_items:
   - 'session    required     pam_mkhomedir.so skel=/etc/skel/ umask=0022'
  become: yes
  when: check_al2.rc == 0

- name: Modify /etc/stns/client/stns.conf
  template :
    src: etc/stns/client/stns.conf.j2
    dest: /etc/stns/client/stns.conf
    owner: root
    group: root
    mode: 0666
    backup: yes
  become: yes
  when: check_al2.rc == 0

- name: Place /usr/local/bin/ssh-chain-wrapper
  template :
    src: usr/local/bin/ssh-chain-wrapper.j2
    dest: /usr/local/bin/ssh-chain-wrapper
    owner: root
    group: root
    mode: 0755
    backup: yes
  become: yes
  when: check_al2.rc == 0

- name: Enable service cache-stnsd, and not touch the state
  service:
    name: cache-stnsd
    enabled: yes
  when: check_al2.rc == 0

- name: Start service cache-stnsd, if not started
  service:
    name: cache-stnsd
    state: started
  when: check_al2.rc == 0

- name: Modify /etc/ssh/sshd_config
  template :
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    backup: yes
  become: yes
  when: check_al2.rc == 0
  notify: "restart sshd"
